version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18    
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - node -v
      - npm install -g yarn
      - yarn install
      - yarn global add gatsby-cli
  build:
    commands:
      - yarn run build:prefix
artifacts:
  files:
    - '**/*'
  base-directory: public
