version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "node -v" 
  pre_build:
    commands:
      - npm install -g yarn
      - yarn install
      - yarn add -g gatsby-cli
  build:
    commands:
      - npm run build
artifacts:
  files:
    - '**/*'
  base-directory: public
