version: 0.2

phases:
  install:
    commands:
      - echo "Installing dependencies..."
      - n 18
  pre_build:
    commands:
      - npm install
  build:
    commands:
      - npm run build
artifacts:
  files:
    - '**/*'
  base-directory: public
